apm install autoclose-html
apm install highlight-selected
apm install linter
apm install linter-htmlhint
apm install linter-jshint
apm install linter-php
apm install linter-markdown
apm install minimap
apm install remote-ftp
apm install split-diff
apm install file-icons
