brew install autoclose-html
brew install highlight-selected
brew install linter
brew install linter-htmlhint
brew install linter-jshint
brew install linter-php
brew install minimap
brew install remote-ftp
brew install split-diff
brew install file-icons
